---
- name: Automatic VM shutdown remediation
  hosts: all

  sources:
    - name: listen for alerts from openshift
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 8001
        data_host_path: ""

  rules:
    - name: VM down
      condition: event.alert is defined
      action:
        print_event:
          pretty: true
#        run_job_template:
#          name: 'vm_startup'
